export enum NotificationEvent {
  TEAM_INVITATION = 'TEAM_INVITATION',
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  REVIEW_CREATED = 'REVIEW_CREATED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
}
