export enum SubscriptionEvent {
  CREATED = 'CREATED',
  UPGRADED = 'UPGRADED',
  DOWNGRADED = 'DOWNGRADED',
  RENEWED = 'RENEWED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  GRACE_STARTED = 'GRACE_STARTED',
  MANUALLY_ACTIVATED = 'MANUALLY_ACTIVATED',
}
