export enum ProfessionalType {
  BARBER = 'BARBER',
  TATTOO_ARTIST = 'TATTOO_ARTIST',
  HAIRDRESSER = 'HAIRDRESSER',
  MANICURE = 'MANICURE',
  ESTHETICIAN = 'ESTHETICIAN',
  LASH_DESIGNER = 'LASH_DESIGNER',
  EYEBROW_DESIGNER = 'EYEBROW_DESIGNER',
}
