export enum TenantSegment {
  BARBERSHOP = 'BARBERSHOP',
  TATTOO_STUDIO = 'TATTOO_STUDIO',
  HAIR_SALON = 'HAIR_SALON',
  NAIL_STUDIO = 'NAIL_STUDIO',
  BEAUTY_SALON = 'BEAUTY_SALON',
  OTHER = 'OTHER',
}
